services:
  - type: web
    name: Jothar Owlbear Rodeo
    runtime: static
    buildCommand: yarn build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    branch: main
    buildFilter:
      paths:
      - src/**/*.js
      - src/**/*.ts
      ignoredPaths:
      - src/**/*.test.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
      - path: /*
        name: X-Robots-Tag
        value: noindex
    envVars:
        - key: REACT_APP_BROKER_URL
          fromService:
            type: web
            name: "Jothar Owlbear Rodeo Backend"
            envVarKey: RENDER_EXTERNAL_URL
        - key: REACT_APP_MAINTENANCE
          value: false
        - key: REACT_APP_VERSION
          value: "1.10.2"
        - key: NODE_VERSION
          value: "16.16.0"
  # A Docker web service
  - type: web
    name: Jothar Owlbear Rodeo Backend
    runtime: docker
    region: oregon # optional (defaults to oregon) check other regions here: https://render.com/docs/regions
    plan: free
    branch: main
    rootDir: ./backend
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: ORIGIN_WHITELIST
        fromService:
          type: web
          name: "Jothar Owlbear Rodeo"
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: "16.16.0"